# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.8.8"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/netbirdio/netbird/releases/download/v0.8.8/netbird_0.8.8_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fb553d0ff65c697b2268e247d2539dae44cdd3399283c03fbae56ac7581d3f51"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/netbirdio/netbird/releases/download/v0.8.8/netbird_0.8.8_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6dceb60beb1e1d3e4584e823f2f32b999f71f528f1dced07b185c76ca40f1630"

      def install
        bin.install "netbird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netbirdio/netbird/releases/download/v0.8.8/netbird_0.8.8_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "586ea51f79af10296c1df0e941e7cf7979fabaeb43e93c6101b7b6af90e9daa8"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/netbirdio/netbird/releases/download/v0.8.8/netbird_0.8.8_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "48b1cab8eccf75e4708a03de2551e32d6b81ef7f1cd93785cf447449709d1de9"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/netbirdio/netbird/releases/download/v0.8.8/netbird_0.8.8_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5e9ef2e10038eaea123f13b2497c3d390fa567c34389d0e278d3bf2757abfe69"

      def install
        bin.install "netbird"
      end
    end
  end

  conflicts_with "wiretrustee"

  test do
    system "#{bin}/netbird version"
  end
end
